# -*- coding: utf-8 -*-
"""movie recommendationed1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEb14O3iDN0sSHNGCDuydT2TIVy2VW_1
"""

# Download the dataset
!wget https://files.grouplens.org/datasets/movielens/ml-100k.zip

# Unzip the dataset
!unzip ml-100k.zip
import pandas as pd

# Load the ratings file (u.data)
ratings = pd.read_csv(
    'ml-100k/u.data',
    sep='\t',
    names=['user_id', 'movie_id', 'rating', 'timestamp']
)

# Load the movie titles file (u.item)
movies = pd.read_csv(
    'ml-100k/u.item',
    sep='|',
    encoding='latin-1',
    usecols=[0, 1],
    names=['movie_id', 'title']
)

# Merge ratings and movies on movie_id
df = pd.merge(ratings, movies, on='movie_id')

# Drop the timestamp (not needed for now)
df.drop(columns='timestamp', inplace=True)

# Show the first few rows
df.head()
print("Shape of the dataset:", df.shape)
print("\nMissing values:\n", df.isnull().sum())

# Basic stats
print("\nRating Summary:\n", df['rating'].describe())


# Pivot the dataframe to create a user-movie matrix
user_movie_matrix = df.pivot_table(index='user_id', columns='title', values='rating')

# Preview the matrix
user_movie_matrix.head()

# Fill missing values with 0 for similarity computation
movie_matrix = user_movie_matrix.fillna(0).T  # Transpose to get movies as rows

from sklearn.metrics.pairwise import cosine_similarity

# Compute cosine similarity between movies
cos_sim = cosine_similarity(movie_matrix)

# Convert to DataFrame for easier access
similarity_df = pd.DataFrame(cos_sim, index=movie_matrix.index, columns=movie_matrix.index)
def recommend_movies(movie_title, num_recommendations=5):
    if movie_title not in similarity_df.columns:
        return "❌ Movie not found in database."

    # Sort the similarity scores for that movie
    scores = similarity_df[movie_title].sort_values(ascending=False)[1:num_recommendations+1]
    return scores
recommend_movies("Star Wars (1977)", 5)

import seaborn as sns
import matplotlib.pyplot as plt

# Top 10 most rated movies
most_rated = df['title'].value_counts().head(10)

plt.figure(figsize=(10, 6))
sns.barplot(x=most_rated.values, y=most_rated.index, palette="coolwarm")
plt.title('Top 10 Most Rated Movies')
plt.xlabel('Number of Ratings')
plt.ylabel('Movie Title')
plt.show()

# distribution of ratings

plt.figure(figsize=(8, 5))
sns.histplot(df['rating'], bins=5, kde=False, color='skyblue')
plt.title('Distribution of Ratings')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

# average_ratings per movie

average_ratings = df.groupby('title')['rating'].mean().sort_values(ascending=False)
top_avg_rated = average_ratings[df['title'].value_counts() > 100].head(10)

plt.figure(figsize=(10, 6))
sns.barplot(x=top_avg_rated.values, y=top_avg_rated.index, palette='viridis')
plt.title('Top 10 Movies by Average Rating (min 100 ratings)')
plt.xlabel('Average Rating')
plt.ylabel('Movie Title')
plt.show()

# Save the user-movie matrix
user_movie_matrix.to_csv("user_movie_matrix.csv")


# Cosine Similarity Matrix

similarity_df.to_csv("cosine_similarity_matrix.csv")

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np

# Load the saved cosine similarity matrix
similarity_df = pd.read_csv('cosine_similarity_matrix.csv', index_col=0)

# Load the movie titles
movie_titles = similarity_df.columns

st.title('Movie Recommendation System')

st.header('Get Recommendations Based on a Movie')
selected_movie = st.selectbox('Select a movie:', movie_titles)
num_recommendations = st.slider('Number of recommendations:', min_value=1, max_value=10, value=5)

# Function to recommend movies based on a selected movie
def recommend_movies(movie_title, num_recommendations=5):
    if movie_title not in similarity_df.columns:
        return "Movie not found in database."

    # Get similarity scores and sort them
    scores = similarity_df[movie_title].sort_values(ascending=False)[1:num_recommendations+1]
    return scores

# Display recommendations when user selects a movie
recommendations = recommend_movies(selected_movie, num_recommendations)

if isinstance(recommendations, pd.Series):
    st.write(f"**Top {num_recommendations} recommendations based on '{selected_movie}':**")
    st.write(recommendations)
else:
    st.write(recommendations)